version: '3.9'
services:
  backend:
    build: ./backend
    container_name: cv-matcher-backend
    env_file:
      - backend/.env
    ports:
      - '8000:8000'
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: cv-matcher-frontend
    depends_on:
      - backend
    ports:
      - '5173:80'
    restart: unless-stopped
