name: Bug report
description: File a bug report
title: 'bug: '
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the issue
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      placeholder: Paste any relevant output
