name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: pip install --no-cache-dir -r backend/requirements.txt
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Build frontend
        working-directory: frontend
        run: |
          npm install --no-audit --no-fund
          npm run build
      - name: Integrate frontend build into backend
        run: cp -r frontend/dist backend/frontend_dist
      - name: Smoke test API
        working-directory: backend
        run: |
          uvicorn main:app --host 127.0.0.1 --port 9000 &
          PID=$!
          sleep 4
          curl -fsS http://127.0.0.1:9000/ || (echo "startup failed" && kill $PID && exit 1)
          kill $PID
